# Generated by Django 6.1.1 on 2026-09-23 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id', 'username'], 'verbose_name': 'Студент', 'verbose_name_plural': 'Студенты'},
        ),
    ]
