[project]
name = "30-rest-framework"
version = "0.1.0"
description = ""
authors = [
    {name = "Maksim Andreev",email = "andrianov_maksim@outlook.com"}
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "openpyxl (>=3.1.5,<4.0.0)",
    "psycopg2 (>=2.9.13,<3.0.0)",
    "redis (>=8.1.0,<9.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
