# Generated by Django 6.1.1 on 2026-09-23 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='Название курса')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='couse/', verbose_name='Фотография')),
                ('description', models.CharField(blank=True, default='Без опиcания', verbose_name='Описание курса')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ['id', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='Название урока')),
                ('description', models.CharField(blank=True, default='Опиcание скоро появится', verbose_name='Описание урока')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='lesson/', verbose_name='Фотография')),
                ('video_link', models.CharField(blank=True, null=True, verbose_name='Сылка на видео')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['id', 'title'],
            },
        ),
    ]
